{% set name = "king" %}
{% set version = "2.2.4" %}

package:
  name: "king"
  version: "2.2.4"

source:
  url: "http://people.virginia.edu/~wc9c/KING/Linux-king.tar.gz"
  sha256: 405e603875d04e19559598f2b27e5e8113d5b4424388a92fa0b40251897c592b

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib

test:
  imports:
    - king

about:
  home: "http://people.virginia.edu/~wc9c/KING/"
  license: INDIVIDUAL
  summary: "`Kinship-based INference for Gwas (KING) is a toolset that makes use of high-throughput SNP data typically seen in a genome-wide association study <http://people.virginia.edu/~wc9c/KING/>`_"

extra:
  recipe-maintainers:
    - your-github-id-here
